administrador/urls.py
from django.urls import path
from administrador import views
app_name = "administrador"

urlpatterns = [
	path('', views.administrador, name='administrador'),
	#CRUD socios
	path('visualizar_socios/', views.administrador_visualizar_socios, name='visualizar_socios'),
	path('agregar_socio/', views.administrador_agregar_socios, name='agregar_socio'),
	path('eliminar_socio/<int:id_socio>/', views.administrador_eliminar_socios, name='eliminar_socio'),
	path('modificar_socio/<int:id_socio>/', views.administrador_modificar_socios, name='modificar_socio'),
	path('descargar_excel_socios/', views.descargar_excel_socios, name='descargar_excel_socios'),



	#CRUD boletas
	path('visualizar_boletas/', views.administrador_visualizar_boletas, name='visualizar_boletas'),
	path('agregar_boleta/', views.adminsitrador_agregar_boleta, name='agregar_boleta'),
	path('eliminar_boleta/<int:id_boleta>/', views.administrador_eliminar_boleta, name='eliminar_boleta'),
	path('modificar_boleta/<int:id_boleta>/', views.administrador_modificar_boleta, name='modificar_boleta'),
	path('validar_boleta/', views.validar_boleta, name='validar_boleta'),
	path('validar_talonario/', views.validar_talonario, name='validar_talonario'),
	path('guardar_boleta/', views.guardar_boleta, name='guardar_boleta'),

	#CRUD usuarios
	path('visualizar_usuarios/', views.administrador_visualizar_usuarios, name='visualizar_usuarios'),
	path('modificar_ususario/<int:id_usuario>/', views.administrador_modificar_usuarios, name='modificar_ususario'),
	path('actualizar_usuario/', views.actualizar_usuario, name='actualizar_usuario'),
	path('agregar_nuevo_usuario/', views.administrador_agregar_usuario, name='agregar_nuevo_usuario'),
	path('agregar_usuario/', views.agregar_usuario, name='agregar_usuario'),
	path('eliminar_usuario/<int:id_usuario>/', views.administrador_eliminar_usuarios, name='eliminar_usuario'),
	
	#CRUD talonario
	path('visualizar_talonarios/', views.administrador_visualizar_talonarios, name='visualizar_talonarios'),
	path('modificar_talonario/<int:id_talonario>/', views.administrador_modificar_talonario, name='modificar_talonario'),
	path('anular_talonario/<int:id_talonario>/', views.administrador_eliminar_talonario, name='anular_talonario'),
	path('agregar_talonario/', views.administrador_agregar_talonario, name='agregar_talonario'),
	path('actualizar_talonario/', views.actualizar_talonario, name='actualizar_talonario'),
	path('guardar_talonario/', views.guardar_talonario, name='guardar_talonario'),
	path('eliminar_talonario/<int:id_talonario>/', views.administrador_eliminar_talonario, name='eliminar_talonario'),

	#CRUD sector
	path('visualizar_sectores/', views.administrador_visualizar_sector, name='visualizar_sectores'),
	path('agregar_sector/', views.administrador_agregar_sector, name='agregar_sector'),
	path('eliminar_sector/<int:id_sector>/', views.administrador_eliminar_sector, name='eliminar_sector'),
	path('modificar_sector/<int:id_sector>', views.administrador_modificar_sector, name='modificar_sector'),
	path('actualizar_sector/', views.actualizar_sector, name='actualizar_sector'),
	path('guardar_sector/', views.guardar_sector, name='guardar_sector'),
	
	

	path('graficar_boletas/', views.graficar_boletas, name='graficar_boletas'),
	path('graficar_usuarios/', views.graficar_usuarios, name='graficar_usuarios'),
]

apps/secretario/urls.py
from django.urls import path
from apps.secretario import views
app_name = "secretario"

urlpatterns = [
	path('', views.secretario, name='secretario'),
	path('ingresar_recaudador/', views.ingresar_recaudador, name='ingresar_recaudador'),
	path('guardar_recaudador/', views.guardar_recaudador, name='guardar_recaudador'),
	path('visualizar_socios/', views.visualizar_socios, name='visualizar_socios'),
	path('modificar_socio/<int:id_socio>/', views.modificar_socio, name='modificar_socio'),
	path('guardar_socio/', views.guardar_socio, name='guardar_socio'),
	path('graficar/',views.graficar, name='graficar'),
	path('estados_cuentas/', views.visualizar_estado_cuenta, name='estados_cuentas'),
	path('visualizar_boletas/<int:id_socio>/', views.visualizar_boletas, name='visualizar_boletas'),
	
]

apps/tesorero/urls.py
from django.urls import path
from apps.tesorero import views
app_name = "tesorero"

urlpatterns = [
	path('', views.tesorero, name='tesorero'),
	path('visualizar_balance/', views.visualizar_balance, name='visualizar_balance'),
	path('crear_balance/', views.crear_balance, name='crear_balance'),
	path('visualizar_socios_activos/', views.visualizar_socios_activos, name='visualizar_socios_activos'),
	path('visualizar_boletas_anuladas/', views.visualizar_boletas_anuladas, name='visualizar_boletas_anuladas'),
	path('editar_boletas_anuladas/<int:id_boleta>/', views.editar_boletas_anuladas, name='editar_boletas_anuladas'),
	path('visualizar_recaudador/', views.visualizar_recaudador, name='visualizar_recaudador'),
	path('guardar_boleta/',views.guardar_boleta, name='guardar_boleta'),
	path('visualizar_detalle_blance/',views.visualizar_detalle_blance, name='visualizar_detalle_blance'),
	path('graficar/',views.graficar, name='graficar'),
	path('visualizar_recaudador/', views.visualizar_recaudador, name='visualizar_recaudador'),
	path('modificar_recaudador/<int:id_recaudador>/', views.modificar_recaudador, name='modificar_recaudador'),
	path('guardar_modificado/', views.guardar_modificado, name='guardar_modificado'),
	path('cargar_datos/<int:trimestre>', views.cargar_datos, name='cargar_datos'),
	path('guardar_balance/', views.guardar_balance, name='guardar_balance'),
	path('modificar_balance/<int:id_balance>', views.modificar_balance, name='modificar_balance'),
	path('guardar_balance_editado/', views.guardar_balance_editado, name='guardar_balance_editado'),
	path('modificar_socio/<int:id_socio>/', views.modificar_socio, name='modificar_socio'),
]

bomba_austria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.login import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.login.urls')),
    path('recaudador/', include('apps.recaudador.urls')),
    path('secretario/', include('apps.secretario.urls')),
    path('tesorero/', include('apps.tesorero.urls')),
    path('administrador/', include('administrador.urls')),
]

handler404 = 'apps.login.views.handler404'
handler500 = 'apps.login.views.handler500' 

apps/secretario/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User, Permission, Group
from django.db import models

# Create your models here.

apps/secretario/views.py
# -*- coding: utf-8 -*-
import datetime
# from __future__ import unicode_literals
from django.shortcuts import render
from apps.recaudador.models import *
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core import serializers
from django.contrib.auth.models import User, Group
from apps.recaudador.models import Profile, Socio
from django.contrib.auth.decorators import login_required, permission_required

def group_check(user):
	groups = Group.objects.get(user = user)
	if groups.name == 'Secretario' or user.is_superuser:
		return True
	else:
		return False

@login_required()
def secretario (request):
	context = {}
	if group_check(request.user):
		template_name = "secretario/inicio.html"
		return render(request,template_name, context)
	else:
		context['messages'] =  "Usted no tiene permisos de Secretario!"
		return render(request, 'login/sin_permisos.html', context)

def graficar (request):
	socios = Socio.objects.order_by('id')
	fecha_actual = datetime.datetime.now()
	fecha_separada = str(fecha_actual).split('-')
	año = fecha_separada[0]
	mes = fecha_separada[1]
	dia = fecha_separada[2]
	datos = {}
	
	for socio in socios:
		if socio.socio_inscripcion != None:
			fecha_inscripcion = str(socio.socio_inscripcion)
			fecha_separada_incripcion = fecha_inscripcion.split('-')
			if fecha_separada_incripcion[0] not in datos.keys():
				datos[fecha_separada_incripcion[0]] = 1
			elif fecha_separada_incripcion[0] in datos.keys():
				datos[fecha_separada_incripcion[0]] += 1
	return JsonResponse(datos)

@login_required()
def ingresar_recaudador(request):
	context = {}
	if group_check(request.user):
		template_name = "secretario/guardar_recaudador.html"
		return render(request,template_name, context)
	else:
		context['messages'] =  "Usted no tiene permisos de Secretario!"
		return render(request, 'login/sin_permisos.html', context)

def guardar_recaudador(request):
	datos = request.POST
	ddatos_string = list(datos.items())
	ddatos_json = json.loads(ddatos_string[0][0])
	for data in ddatos_json:
		if 'Nombre_user' in data.keys():
			nombre_usuario = data['Nombre_user']
		if 'Nombre' in data.keys():
			nombre = data['Nombre']
		if 'Apellido' in data.keys():
			apellido =  data['Apellido']
		if 'email' in data.keys():
			email = data['email']
		if 'password' in data.keys():
			contrasena = data['password']
	if not User.objects.filter(username = nombre_usuario):
		grupo = Group.objects.get(name = 'Recaudador')
		new_user = User.objects.create_user(
			username = nombre_usuario,
			first_name = nombre,
			last_name = apellido,
			email = email,
			password = contrasena)
		new_user.is_active = True
		new_user.is_staff = False
		new_user.is_superuser = False
		new_user.save()
		new_user.groups.add(grupo)
		perfil_recaudador = Profile()
		perfil_recaudador.user = new_user
		perfil_recaudador.save()
		return HttpResponse(JsonResponse({"respuesta":"correcto"}), content_type='applicaction/json')
	else:
		usuario_existe = "Nombre usuario ya existe"
		return HttpResponse(JsonResponse({"respuesta":usuario_existe}), content_type='applicaction/json')

@login_required()
def visualizar_socios(request):
	context = {}
	if group_check(request.user):
		template_name = "secretario/visualizar_socios.html"
		socios = Socio.objects.all()
		context['socios'] =  socios
		return render(request,template_name, context)
	else:
		context['messages'] =  "Usted no tiene permisos de Secretario!"
		return render(request, 'login/sin_permisos.html', context)

@login_required()
def modificar_socio(request, id_socio):
	context = {}
	if group_check(request.user):
		template_name = "secretario/modificar_socio.html"
		data = Socio.objects.get(id = id_socio)
		fecha = data.socio_fecha_nacimiento
		context['socio'] = data
		context['fecha'] = fecha
		context['sectores'] = Sector.objects.all()
		return render(request,template_name, context)
	else:
		context['messages'] =  "Usted no tiene permisos de Secretario!"
		return render(request, 'login/sin_permisos.html', context)

def guardar_socio(request):
	datos = request.POST
	ddatos_string = list(datos.items())
	ddatos_json = json.loads(ddatos_string[0][0])
	socio = 0
	for data in ddatos_json:
		if 'codigo' in data.keys() :
			socio = int(data['codigo'])
		if 'Nombre' in data.keys():
			nombre = data['Nombre']
		if 'Rut' in data.keys():
			rut = data['Rut']
		if 'Direccion' in data.keys():
			direccion = data['Direccion']
		if 'Sector' in data.keys():
			sector = data['Sector']
		if 'F_nac' in data.keys():
			if data['F_nac'] != '':
				nacimiento = data['F_nac']
		if 'Monto' in data.keys():
			monto = data['Monto']
		if 'Pago' in data.keys():
			pago = data['Pago']
		if 'estado' in data.keys():
			Estado = data['estado']
	if Socio.objects.get(id = socio):
		sec = Sector.objects.get(id = sector)
		Socio.objects.filter(id = socio).update(socio_nombre = nombre)
		Socio.objects.filter(id = socio).update(socio_rut = rut)
		Socio.objects.filter(id = socio).update(socio_direccion = direccion)
		Socio.objects.filter(id = socio).update(socio_sector = sector)
		Socio.objects.filter(id = socio).update(socio_aporte = monto)
		Socio.objects.filter(id = socio).update(socio_dia_pago = pago)
		Socio.objects.filter(id = socio).update(socio_estado = Estado)
		return HttpResponse(JsonResponse({"respuesta" : "correcto"}), content_type='applicaction/json')
	else:
		return HttpResponse(JsonResponse({"respuesta" : "incorrecto"}), content_type='applicaction/json')

@login_required()
def visualizar_estado_cuenta(request):
	context = {}
	if group_check(request.user):
		template_name = 'secretario/visualizar_estado_cuenta.html'
		context = {}
		boletas_pagas = {}
		boletas_teoricas = {}
		x = datetime.datetime.now()
		if x.day < 10 and x.month < 10:
			fecha_actual = str(x.year) + "-" + "0" + str(x.month) + "-" + "0" + str(x.day)
		elif x.day < 10 and x.month >= 10:
			fecha_actual = str(x.year) + "-" + str(x.month) + "-" + "0" + str(x.day)
		elif x.day >= 10 and x.month >= 10:
			fecha_actual = str(x.year) + "-" + str(x.month) + "-" + str(x.day)
		elif x.day >= 10 and x.month < 10:
			fecha_actual = str(x.year) + "-" + "0" + str(x.month) + "-" + str(x.day)
		socios = Socio.objects.all()
		try:
			for socio in socios:
				if socio not in boletas_pagas.keys():
					boletas_pagas[socio] = Boleta.objects.filter(boleta_socio = socio.id).filter(boleta_fecha__range = [socio.socio_inscripcion, fecha_actual]).count()
					print(boletas_pagas)
					contador = 0
					inscripcion_ano= int(socio.socio_inscripcion.year)
					inscripcion_mes = int(socio.socio_inscripcion.month)
					while inscripcion_ano <= int(x.year):
						while inscripcion_mes <= int(x.month):
							contador += 1
							inscripcion_mes += 1
						inscripcion_ano += 1
					boletas_teoricas[socio] = contador
			context['boletas'] = boletas_pagas
			context['teorico'] = boletas_teoricas

			return render(request, template_name, context)
		except:
			return render(request, template_name, context)
	else:
		context['messages'] =  "Usted no tiene permisos de Secretario!"
		return render(request, 'login/sin_permisos.html', context)
	
@login_required()
def visualizar_boletas(request, id_socio):
	context = {}
	if group_check(request.user):
		template_name = 'secretario/visualizar_boletas.html'
		context = {}
		x = datetime.datetime.now()
		if x.day < 10 and x.month < 10:
			fecha_actual = str(x.year) + "-" + "0" + str(x.month) + "-" + "0" + str(x.day)
		elif x.day < 10 and x.month >= 10:
			fecha_actual = str(x.year) + "-" + str(x.month) + "-" + "0" + str(x.day)
		elif x.day >= 10 and x.month >= 10:
			fecha_actual = str(x.year) + "-" + str(x.month) + "-" + str(x.day)
		elif x.day >= 10 and x.month < 10:
			fecha_actual = str(x.year) + "-" + "0" + str(x.month) + "-" + str(x.day)

		boletas = Boleta.objects.filter(boleta_socio = id_socio).filter(boleta_estado = True).filter(boleta_fecha__lte = fecha_actual )
		context['boletas'] = boletas
		print (context)
		return render(request, template_name, context)
	else:
		context['messages'] =  "Usted no tiene permisos de Secretario!"
		return render(request, 'login/sin_permisos.html', context)

apps/secretario/templates/secretario/visualizar_socios.html
 <!DOCTYPE html>
{% load staticfiles %}
<html lang="es">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Mouldifi - A fully responsive, HTML5 based admin theme">
		<meta name="keywords" content="Responsive, HTML5, admin theme, business, professional, Mouldifi, web design, CSS3">
		<title>Bomba Austria</title>

		<!-- Site favicon -->
		<link rel='shortcut icon' type='image/x-icon' href='{% static "images/favicon.ico" %}'> 
		<!-- /site favicon -->

		<!-- Entypo font stylesheet -->
		<link href="{% static "mouldifi/light/css/entypo.css" %}" rel="stylesheet">
		<!-- /entypo font stylesheet -->

		<!-- Font awesome stylesheet -->
		<link href="{% static "mouldifi/light/css/font-awesome.min.css" %}"rel="stylesheet">
		<!-- /font awesome stylesheet -->

		<!-- Bootstrap stylesheet min version -->
		<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
		<!-- /bootstrap stylesheet min version -->

		<!-- Mouldifi core stylesheet -->
		<link href="{% static "mouldifi/light/css/mouldifi-core.css" %}" rel="stylesheet">
		<!-- /mouldifi core stylesheet -->

		<link href="{% static "mouldifi/light/css/mouldifi-forms.css" %}" rel="stylesheet">

		<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
		<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.min.css">


		<link href="{% static "mouldifi/light/css/plugins/datepicker/bootstrap-datepicker.css" %}" rel="stylesheet">
		<link href="{% static "mouldifi/light/css/plugins/colorpicker/bootstrap-colorpicker.css" %} rel="stylesheet">
		<link href="{% static "mouldifi/light/css/plugins/nouislider/nouislider.css" %} rel="stylesheet">
		<link href="{% static "mouldifi/light/css/mouldifi-forms.css" %}" rel="stylesheet" >
	</head>
	<!-- <body oncontextmenu="return false" onkeydown="return false"> -->
	<body>
		<!-- Page container -->
		<div class="page-container">
			<!-- Page Sidebar -->
			<div class="page-sidebar">
				<!-- Site header  -->
				<header class="site-header">
					<div class="site-logo">
						<a href="">
							<img src=" {% static "/images/logo-bomba.jpg" %}" alt="Bomba Austria" title="Bomba Austria">
						</a>
					</div>
					<div class="sidebar-collapse hidden-xs">
						<a class="sidebar-collapse-icon" href="#">
							<i class="icon-menu"></i>
						</a>
					</div>
					<div class="sidebar-mobile-menu visible-xs">
						<a data-target="#side-nav" data-toggle="collapse" class="mobile-menu-icon" href="#">
							<i class="icon-menu"></i>
						</a>
					</div>
				</header>
				<!-- /site header -->

				<!-- Main navigation -->
				<ul id="side-nav" class="main-menu navbar-collapse collapse">
					<li id="dashboard" class="">
						<a href="{% url 'secretario:secretario' %}">
							<i class="icon-gauge"></i><span class="title">Dashboard</span>
						</a>
					</li>
			
					<li id="secretario" class="has-sub">
						<a href="">
							<i class="icon-credit-card"></i><span class="title">Ingresar Recaudador</span>
						</a>
						<ul id="navPagos" class="nav collapse"> <!-- nav -->
							<li id="ingresarRecaudador" class="">
								<a href="{% url 'secretario:ingresar_recaudador' %}"><span class="title">Ingresar Recaudador</span></a>
							</li>
						</ul>
					</li>
					
					<li id="recaudador" class="has-sub">
						<a href="">
							<i class="icon-credit-card"></i><span class="title">Visualizar datos de los Socios Cooperadors</span>
						</a>
						<ul id="navPagos" class="nav collapse"> <!-- nav -->
							<li id="verdatos" class="">
								<a href="{% url 'secretario:visualizar_socios' %}"><span class="title">Visualizar datos de los Socios Cooperadors</span></a>
							</li>
						</ul>
					</li>
					<li id="recaudador" class="has-sub">
						<a href="">
							<i class="icon-credit-card"></i><span class="title">Visualizar Estados de Cuenta del mes</span>
						</a>
						<ul id="navPagos" class="nav collapse"> <!-- nav -->
							<li id="verdatos" class="">
								<a href="{% url 'secretario:estados_cuentas' %}"><span class="title">Visualizar Estados de Cuenta del mes</span></a>
							</li>
						</ul>
					</li>

				</ul>
				<!-- /main navigation -->	
  			</div>
  			<!-- /page sidebar -->

  			<div class="main-content">
				<!-- Main header -->
				<div class="main-header row">
					<div class="col-sm-6 col-xs-7 pull-right">
						<!-- User info -->
						<ul class="user-info pull-right">          
							<li class="profile-info dropdown">
								<a data-toggle="dropdown" class="dropdown-toggle" href="#" aria-expanded="false">
									<img width="44" class="img-circle avatar" alt="" src="{% static "/images/man-3.jpg" %}"> {{request.user.get_full_name}} <span class="caret"></span>
								</a>
								<ul class="dropdown-menu">
									<li>
										<a href="/logout"><i class="icon-logout"></i>Cerrar Sesión</a>
									</li>
								</ul>
							</li>
						</ul>
						<!-- /user info -->
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<div class="panel panel-default">
							<div class="panel-heading clearfix">
								<h3 class="panel-title">Visualizar Socios Cooperadores</h3>
								<ul class="panel-tool-options"> 
									<li>
										<a data-rel="reload" href="#"><i class="icon-arrows-ccw"></i></a>
									</li>
								</ul>
							</div>
							<div class="panel-body">
								<div class="table-responsive">
									<table id="example" class="table table-striped table-bordered table-hover dataTables-example">
									    <thead>
											<tr>
												<th>ID</th>
												<th>Nombre</th>
												<th>Direccion</th>
												<th>Sector</th>
												<th>Fecha de Nacimiento</th>
												<th>Fono</th>
												<th>Aporte</th>
												<th>Dia de pago</th>
												<th>Estado</th>
												<th>Editar</th>
											</tr>
									    </thead>
									    <tbody>
									    	{% if socios %}
												{% for socio in socios %}
												<tr>
													<td>{{socio.id}}</td>
													<td>{{socio.socio_nombre}}</td>
													<td>{{socio.socio_direccion}}</td>
													<td>{{socio.socio_sector.sector_nombre}}</td>
													<td>{{socio.socio_fecha_nacimiento}}</td>
													<td>{{socio.socio_telefono}}</td>
													<td>{{socio.socio_aporte}}</td>
													<td>{{socio.socio_dia_pago}}</td>
													<td>{{socio.socio_estado}}</td>
													<td>
														<a href="{% url 'secretario:modificar_socio' socio.id %}" type="button" class="btn btn-primary btn-outline">Modificar</a>
													</td>
												</tr>
												{% endfor %}
											{% else %}
												<tr>
													<td>No hay datos</td>
													<td>-</td>
													<td>-</td>
													<td>-</td>
													<td>-</td>
													<td>-</td>
													<td>-</td>
													<td>-</td>
													<td>-</td>
													<td>-</td>
												</tr>
											{% endif %}
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

<!--Load JQuery-->
<script src="{% static "mouldifi/light/js/jquery.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/bootstrap.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/metismenu/jquery.metisMenu.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/blockui-master/jquery-ui.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/blockui-master/jquery.blockUI.js" %}"></script>

<!--DataTables-->
<script src="{% static "mouldifi/light/js/plugins/datatables/jquery.dataTables.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/datatables/dataTables.bootstrap.min.js" %}></script>
<script src="{% static "mouldifi/light/js/plugins/datatables/extensions/Buttons/js/dataTables.buttons.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/datatables/jszip.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/datatables/pdfmake.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/datatables/vfs_fonts.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/datatables/extensions/Buttons/js/buttons.html5.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/datatables/extensions/Buttons/js/buttons.colVis.js" %}"></script>

<!--Float Charts-->
<script src="{% static "mouldifi/light/js/plugins/flot/jquery.flot.min.js" %}></script>
<script src="{% static "mouldifi/light/js/plugins/flot/jquery.flot.tooltip.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/flot/jquery.flot.resize.min.js" %}"></script>
<script src="{%static "mouldifi/light/js/plugins/flot/jquery.flot.selection.min.js" %}"></script>        
<script src="{% static "mouldifi/light/js/plugins/flot/jquery.flot.pie.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/flot/jquery.flot.time.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/functions.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/flot/jquery.flot.canvas.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/datepicker/bootstrap-datepicker.js" %}"></script>
<script>
	$('#example').DataTable({
		language: {
	        "decimal": "",
	        "emptyTable": "No hay información",
	        "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
	        "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
	        "infoFiltered": "(Filtrado de _MAX_ total entradas)",
	        "infoPostFix": "",
	        "thousands": ",",
	        "lengthMenu": "Mostrar _MENU_ Entradas",
	        "loadingRecords": "Cargando...",
	        "processing": "Procesando...",
	        "search": "Buscar:",
	        "zeroRecords": "Sin resultados encontrados",
	        "paginate": {
	            "first": "Primero",
	            "last": "Ultimo",
	            "next": "Siguiente",
	            "previous": "Anterior"
	        }
	    }
	});
</script>