administrador/urls.py
from django.urls import path
from administrador import views
app_name = "administrador"

urlpatterns = [
	path('', views.administrador, name='administrador'),
	#CRUD socios
	path('visualizar_socios/', views.administrador_visualizar_socios, name='visualizar_socios'),
	path('agregar_socio/', views.administrador_agregar_socios, name='agregar_socio'),
	path('eliminar_socio/<int:id_socio>/', views.administrador_eliminar_socios, name='eliminar_socio'),
	path('modificar_socio/<int:id_socio>/', views.administrador_modificar_socios, name='modificar_socio'),
	path('descargar_excel_socios/', views.descargar_excel_socios, name='descargar_excel_socios'),



	#CRUD boletas
	path('visualizar_boletas/', views.administrador_visualizar_boletas, name='visualizar_boletas'),
	path('agregar_boleta/', views.adminsitrador_agregar_boleta, name='agregar_boleta'),
	path('eliminar_boleta/<int:id_boleta>/', views.administrador_eliminar_boleta, name='eliminar_boleta'),
	path('modificar_boleta/<int:id_boleta>/', views.administrador_modificar_boleta, name='modificar_boleta'),
	path('validar_boleta/', views.validar_boleta, name='validar_boleta'),
	path('validar_talonario/', views.validar_talonario, name='validar_talonario'),
	path('guardar_boleta/', views.guardar_boleta, name='guardar_boleta'),

	#CRUD usuarios
	path('visualizar_usuarios/', views.administrador_visualizar_usuarios, name='visualizar_usuarios'),
	path('modificar_ususario/<int:id_usuario>/', views.administrador_modificar_usuarios, name='modificar_ususario'),
	path('actualizar_usuario/', views.actualizar_usuario, name='actualizar_usuario'),
	path('agregar_nuevo_usuario/', views.administrador_agregar_usuario, name='agregar_nuevo_usuario'),
	path('agregar_usuario/', views.agregar_usuario, name='agregar_usuario'),
	path('eliminar_usuario/<int:id_usuario>/', views.administrador_eliminar_usuarios, name='eliminar_usuario'),
	
	#CRUD talonario
	path('visualizar_talonarios/', views.administrador_visualizar_talonarios, name='visualizar_talonarios'),
	path('modificar_talonario/<int:id_talonario>/', views.administrador_modificar_talonario, name='modificar_talonario'),
	path('anular_talonario/<int:id_talonario>/', views.administrador_eliminar_talonario, name='anular_talonario'),
	path('agregar_talonario/', views.administrador_agregar_talonario, name='agregar_talonario'),
	path('actualizar_talonario/', views.actualizar_talonario, name='actualizar_talonario'),
	path('guardar_talonario/', views.guardar_talonario, name='guardar_talonario'),
	path('eliminar_talonario/<int:id_talonario>/', views.administrador_eliminar_talonario, name='eliminar_talonario'),

	#CRUD sector
	path('visualizar_sectores/', views.administrador_visualizar_sector, name='visualizar_sectores'),
	path('agregar_sector/', views.administrador_agregar_sector, name='agregar_sector'),
	path('eliminar_sector/<int:id_sector>/', views.administrador_eliminar_sector, name='eliminar_sector'),
	path('modificar_sector/<int:id_sector>', views.administrador_modificar_sector, name='modificar_sector'),
	path('actualizar_sector/', views.actualizar_sector, name='actualizar_sector'),
	path('guardar_sector/', views.guardar_sector, name='guardar_sector'),
	
	

	path('graficar_boletas/', views.graficar_boletas, name='graficar_boletas'),
	path('graficar_usuarios/', views.graficar_usuarios, name='graficar_usuarios'),
]

bomba_austria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.login import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.login.urls')),
    path('recaudador/', include('apps.recaudador.urls')),
    path('secretario/', include('apps.secretario.urls')),
    path('tesorero/', include('apps.tesorero.urls')),
    path('administrador/', include('administrador.urls')),
]

handler404 = 'apps.login.views.handler404'
handler500 = 'apps.login.views.handler500' 

administrador/models.py
from django.db import models

# Create your models here.

administrador/views.py
# -*- coding: utf-8 -*-
import datetime
# from __future__ import unicode_literals
from django.shortcuts import render
from apps.recaudador.models import *
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
import json
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core import serializers
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required, permission_required
from apps.recaudador.models import *


# Create your views here.

@login_required()
def administrador(request):
	context = {}
	if request.user.is_staff and request.user.is_superuser:
		template_name = "inicio.html"
		return render(request, template_name, context)
	else:
		context['messages'] =  "Usted no tiene permisos de  Administrador!"
		context['grupo'] =groups
		return render(request, 'login/sin_permisos.html', context)

@login_required()
#crud de usuarios
def administrador_visualizar_usuarios(request):
	template_name = "visualizar_usuarios.html"
	context = {}
	if request.user.is_staff and request.user.is_superuser:
		context['usuarios'] = User.objects.all()
		# context['grupos'] = Group.objects.all()
		return render(request, template_name, context)
	else:
		context['messages'] =  "Usted no tiene permisos de  Administrador!"
		# context['grupo'] =groups
		return render(request, 'login/sin_permisos.html', context)

@login_required()
def administrador_eliminar_usuarios(request,id_usuario):
	usuario = User.objects.get(id=id_usuario)
	if Profile.objects.filter(user = usuario.id):
		profile = Profile.objects.get(user = usuario.id)
		if profile.delete():
			usuario.delete()
			return HttpResponseRedirect('/administrador/visualizar_usuarios/')

@login_required()
def administrador_modificar_usuarios(request,id_usuario):
	template_name = "crud_usuario/modificar_usuario.html"
	context = {}
	if request.user.is_staff and request.user.is_superuser:
		context['usuarios'] = User.objects.get(id = id_usuario)
		context['grupos'] = Group.objects.get(user = context['usuarios'])
		return render(request, template_name, context)
	else:
		context['messages'] =  "Usted no tiene permisos de  Administrador!"
		# context['grupo'] =groups
		return render(request, 'login/sin_permisos.html', context)

@login_required()
def administrador_agregar_usuario(request):
	template_name = "crud_usuario/agregar_usuario.html"
	context = {}
	if request.user.is_staff and request.user.is_superuser:
		context['sectores'] = Sector.objects.all()
		return render(request, template_name, context)
	else:
		context['messages'] =  "Usted no tiene permisos de  Administrador!"
		# context['grupo'] =groups
		return render(request, 'login/sin_permisos.html', context)

def actualizar_usuario(request):
	datos = request.POST
	ddatos_string = list(datos.items())
	ddatos_json = json.loads(ddatos_string[0][0])
	print (ddatos_json)
	for data in ddatos_json:
		if 'id' in data.keys():
			id = data['id']
		if 'Nombre_user' in data.keys():
			nombre_usuario = data['Nombre_user']
		if 'Nombre' in data.keys():
			primer_nombre = data['Nombre']
		if 'Apellido' in data.keys():
			apellido = data['Apellido']
		if 'correo' in data.keys():
			correo = data['correo']
		if 'password' in data.keys():
			password = data['password']
		if 'password2' in data.keys():
			pass
		if 'es_staff' in data.keys():
			es_staff = data['es_staff']
		if 'is_superuser' in data.keys():
			super_user = data['is_superuser']
		if 'es_recaudador' in data.keys():
			es_recaudador = data['es_recaudador']
		if 'es_secretario' in data.keys():
			es_secretario = data['es_secretario']
		if 'es_tesorero' in data.keys():
			es_tesorero = data['es_tesorero']
		if 'es_admin' in data.keys():
			es_admin = data['es_admin']
		if 'estado' in data.keys():
			estado = data['estado']
	User.objects.filter(id=id).update(username = nombre_usuario)
	User.objects.filter(id=id).update(first_name = primer_nombre)
	User.objects.filter(id=id).update(last_name = apellido)
	User.objects.filter(id=id).update(email = correo)
	User.objects.get(id=id).set_password(password)
	User.objects.filter(id=id).update(is_staff = es_staff)
	User.objects.filter(id=id).update(is_superuser = super_user)
	User.objects.filter(id=id).update(is_active = estado)
	if es_recaudador == 'True':
		usuario = User.objects.get(id=id)
		usuario.groups.clear()
		grupo = Group.objects.get(name = 'Recaudador')
		usuario.groups.add(grupo)
	if es_secretario == 'True':
		usuario = User.objects.get(id=id)
		usuario.groups.clear()
		grupo = Group.objects.get(name = 'Secretario')
		usuario.groups.add(grupo)
	if es_tesorero == 'True':
		usuario = User.objects.get(id=id)
		usuario.groups.clear()
		grupo = Group.objects.get(name = 'Tesorero')
		usuario.groups.add(grupo)
	if es_admin == 'True':
		usuario = User.objects.get(id=id)
		usuario.groups.clear()
		grupo = Group.objects.get(name = 'administrador')
		usuario.groups.add(grupo)

	return HttpResponse(JsonResponse({"respuesta":"correcto"}), content_type='applicaction/json')

def agregar_usuario(request):
	datos = request.POST
	ddatos_string = list(datos.items())
	ddatos_json = json.loads(ddatos_string[0][0])
	for data in ddatos_json:
		if 'id' in data.keys():
			id = data['id']
		if 'Nombre_user' in data.keys():
			nombre_usuario = data['Nombre_user']
		if 'Nombre' in data.keys():
			primer_nombre = data['Nombre']
		if 'Apellido' in data.keys():
			apellido = data['Apellido']
		if 'correo' in data.keys():
			correo = data['correo']
		if 'password' in data.keys():
			password = data['password']
		if 'password2' in data.keys():
			pass
		if 'sector' in data.keys():
			sector = data['sector']
		if 'es_staff' in data.keys():
			es_staff = data['es_staff']
		if 'is_superuser' in data.keys():
			super_user = data['is_superuser']
		if 'es_recaudador' in data.keys():
			es_recaudador = data['es_recaudador']
		if 'es_secretario' in data.keys():
			es_secretario = data['es_secretario']
		if 'es_tesorero' in data.keys():
			es_tesorero = data['es_tesorero']
		if 'es_admin' in data.keys():
			es_admin = data['es_admin']
		if 'pertenece' in data.keys():
			pertenece = data['pertenece']

	if not User.objects.filter(username = nombre_usuario):
		new_user = User.objects.create_user(
			username = nombre_usuario,
			first_name = primer_nombre,
			last_name = apellido,
			email = correo,
			password = password)
		new_user.is_active = True
		new_user.is_staff = es_staff
		new_user.is_superuser = super_user
		new_user.save()
		if es_recaudador == 'True':
			grupo = Group.objects.get(name = 'Recaudador')
			new_user.groups.add(grupo)
		if es_secretario == 'True':
			grupo = Group.objects.get(name = 'Secretario')
			new_user.groups.add(grupo)
		if es_tesorero == 'True':
			grupo = Group.objects.get(name = 'Tesorero')
			new_user.groups.add(grupo)
		nuevo_perfil = Profile()
		nuevo_perfil.user = new_user
		nuevo_perfil.sector = Sector.objects.get(id = int(sector))
		nuevo_perfil.pertenece_compania = pertenece
		nuevo_perfil.save()
		
		return HttpResponse(JsonResponse({"respuesta":"correcto"}), content_type='applicaction/json')
	else:
		usuario_existe = "Nombre usuario ya existe"
		return HttpResponse(JsonResponse({"respuesta":usuario_existe}), content_type='applicaction/json')


#crud de boleta
@login_required()
def administrador_visualizar_boletas(request):
	template_name = "visualizar_boletas.html"
	context = {}
	if request.user.is_staff and request.user.is_superuser:
		context['boletas'] = Boleta.objects.all()
		return render(request, template_name, context)
	else:
		context['messages'] =  "Usted no tiene permisos de  Administrador!"
		context['grupo'] =groups
		return render(request, 'login/sin_permisos.html', context)

@login_required()
def administrador_eliminar_boleta(request,id_boleta):
	boleta = Boleta.objects.get(id = id_boleta)
	if boleta.delete():
		return HttpResponseRedirect('/administrador/visualizar_boletas/')

@login_required()
def administrador_modificar_boleta(request,id_boleta):
	template_name = 'crud_boleta/modificar_boleta.html'
	context = {}
	if request.user.is_staff and request.user.is_superuser:
		context = {}
		context['boleta'] = Boleta.objects.get(id = id_boleta)
		fecha = str(context['boleta'].boleta_fecha)
		fecha_separada = fecha.split('-')
		context['fecha'] = fecha_separada[0] + "-" + fecha_separada[1] + "-" + fecha_separada[2]
		grupo = Group.objects.get(name = 'Recaudador')
		recaudadores = User.objects.filter(groups = grupo.id)
		context['recaudadores'] = recaudadores
		context['socios'] = Socio.objects.all().order_by('socio_nombre')
		return render(request, template_name, context)
	else:
		context['messages'] =  "Usted no tiene permisos de  Administrador!"
		context['grupo'] =groups
		return render(request, 'login/sin_permisos.html', context)

def validar_boleta(request):
	id = request.POST['id']
	if Boleta.objects.filter(boleta_numero = id):
		mensaje = "Boleta Existente"
	else:
		mensaje = 'OK'

	return HttpResponse(JsonResponse({'respuesta' : mensaje}), content_type='applicaction/json')

def validar_talonario(request):
	id = request.POST['id']
	if Talonario.objects.filter(id = id):
		mensaje = 'OK'
	else:
		mensaje = "Talonario No Existe"

	return HttpResponse(JsonResponse({'respuesta' : mensaje}), content_type='applicaction/json')

login_required()
def adminsitrador_agregar_boleta(request):
	template_name = 'crud_boleta/agregar_boleta.html'
	context = {}
	if request.user.is_staff and request.user.is_superuser:
		grupo = Group.objects.get(name = 'Recaudador')
		recaudadores = User.objects.filter(groups = grupo.id).filter(is_active = True)
		context['recaudadores'] = recaudadores
		context['socios'] = Socio.objects.filter(socio_estado = 'Activo')
		context['talonarios'] = Talonario.objects.filter(talonario_estado = True)
		context['sectores'] = Sector.objects.all()
		return render(request, template_name, context)
	else:

administrador/templates/visualizar_boletas.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="es">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Mouldifi - A fully responsive, HTML5 based admin theme">
		<meta name="keywords" content="Responsive, HTML5, admin theme, business, professional, Mouldifi, web design, CSS3">
		<title>Bomba Austria</title>

		<!-- Site favicon -->
		<link rel='shortcut icon' type='image/x-icon' href='{% static "images/favicon.ico" %}'> 
		<!-- /site favicon -->

		<!-- Entypo font stylesheet -->
		<link href="{% static "mouldifi/light/css/entypo.css" %}" rel="stylesheet">
		<!-- /entypo font stylesheet -->

		<!-- Font awesome stylesheet -->
		<link href="{% static "mouldifi/light/css/font-awesome.min.css" %}"rel="stylesheet">
		<!-- /font awesome stylesheet -->

		<!-- Bootstrap stylesheet min version -->
		<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
		<!-- /bootstrap stylesheet min version -->

		<!-- Mouldifi core stylesheet -->
		<link href="{% static "mouldifi/light/css/mouldifi-core.css" %}" rel="stylesheet">
		<!-- /mouldifi core stylesheet -->

		<link href="{% static "mouldifi/light/css/mouldifi-forms.css" %}" rel="stylesheet">

		<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
		<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.min.css">


		<link href="{% static "mouldifi/light/css/plugins/datepicker/bootstrap-datepicker.css" %}" rel="stylesheet">
		<link href="{% static "mouldifi/light/css/plugins/colorpicker/bootstrap-colorpicker.css" %} rel="stylesheet">
		<link href="{% static "mouldifi/light/css/plugins/nouislider/nouislider.css" %} rel="stylesheet">
		<link href="{% static "mouldifi/light/css/mouldifi-forms.css" %}" rel="stylesheet" >
	</head>
	<!-- <body oncontextmenu="return false" onkeydown="return false"> -->
	<body>
		<!-- Page container -->
		<div class="page-container">
			<!-- Page Sidebar -->
			<div class="page-sidebar">
				<!-- Site header  -->
				<header class="site-header">
					<div class="site-logo">
						<a href="">
							<img src=" {% static "/images/logo-bomba.jpg" %}" alt="Bomba Austria" title="Bomba Austria">
						</a>
					</div>
					<div class="sidebar-collapse hidden-xs">
						<a class="sidebar-collapse-icon" href="#">
							<i class="icon-menu"></i>
						</a>
					</div>
					<div class="sidebar-mobile-menu visible-xs">
						<a data-target="#side-nav" data-toggle="collapse" class="mobile-menu-icon" href="#">
							<i class="icon-menu"></i>
						</a>
					</div>
				</header>
				<!-- /site header -->
				<!-- Main navigation -->
				<ul id="side-nav" class="main-menu navbar-collapse collapse">
					<li id="dashboard" class="">
						<a href="/administrador/">
							<i class="icon-gauge"></i><span class="title">Dashboard</span>
						</a>
					</li>
					<li id="pagos" class="has-sub">
						<a href="">
							<i class="icon-credit-card"></i><span class="title">Visualizar Boletas</span>
						</a>
						<ul id="navPagos" class="nav collapse">
							<li id="realizarPago" class="">
								<a href="/administrador/visualizar_boletas/"><span class="title">Visualuzar Boletas</span>
								</a>
							</li>
						</ul>
					</li>

		
					<li id="pagos" class="has-sub">
						<a href="">
							<i class="icon-credit-card"></i><span class="title">Visualizar Socio Cooperador</span>
						</a>
						<ul id="navPagos" class="nav collapse"> <!-- nav -->
							<li id="realizarPago" class="">
								<a href="/administrador/visualizar_socios/"><span class="title">Visualizar Socio Cooperador</span>
								</a>
							</li>
						</ul>
					</li>

					<li id="pagos" class="has-sub">
						<a href="<?php echo base_url('')?>">
							<i class="icon-credit-card"></i><span class="title">Visualizar Talonarios</span>
						</a>
						<ul id="navPagos" class="nav collapse"> <!-- nav -->
							<li id="realizarPago" class="">
								<a href="/administrador/visualizar_talonarios/"><span class="title">Visualizar Talonarios</span>
								</a>
							</li>
						</ul>
					</li>

					<li id="pagos" class="has-sub">
						<a href="<?php echo base_url('')?>">
							<i class="icon-credit-card"></i><span class="title">Visualizar Usuarios</span>
						</a>
						<ul id="navPagos" class="nav collapse"> <!-- nav -->
							<li id="realizarPago" class="">
								<a href="/administrador/visualizar_usuarios/"><span class="title">Visualizar Usuarios</span>
								</a>
							</li>
						</ul>
					</li>

					<li id="pagos" class="has-sub">
						<a href="">
							<i class="icon-credit-card"></i><span class="title">Visualizar Sectores</span>
						</a>
						<ul id="navPagos" class="nav collapse"> <!-- nav -->
							<li id="realizarPago" class="">
								<a href="/administrador/visualizar_sectores"><span class="title">Visualizar Sectores</span>
								</a>
							</li>
						</ul>
					</li>
				</ul>
			<!-- /main navigation -->	
			</div>
			<!-- /page sidebar -->
	  		<div class="main-content">
				<!-- Main header -->
				<div class="main-header row">
					<div class="col-sm-6 col-xs-7 pull-right">
						<!-- User info -->
						<ul class="user-info pull-right">          
							<li class="profile-info dropdown">
								<a data-toggle="dropdown" class="dropdown-toggle" href="#" aria-expanded="false">
									<img width="44" class="img-circle avatar" alt="" src="{% static "/images/man-3.jpg" %}"> {{request.user.get_full_name}} <span class="caret"></span>
								</a>
								<ul class="dropdown-menu">
									<li>
										<a href="/logout"><i class="icon-logout"></i>Cerrar Sesión</a>
									</li>
								</ul>
							</li>
						</ul>
						<!-- /user info -->
					</div>
				</div>
				<h1 class="page-title">Administrador </h1>
				<a href="{% url 'administrador:agregar_boleta' %}" type="button" class="btn btn-primary btn-outline">Agregar Boleta</a>
				<br><br>
				<!-- Main content -->
				<div class="main-content-20">
					<div class="table-responsive">
						<table id="example" class="table table-striped table-bordered table-hover dataTables-example">
							<thead>
								<tr>
									<th>Numero de boleta</th>
									<th>Boleta Fecha</th>
									<th>Nombre Socio</th>
									<th>Aporte Boleta</th>
									<th>Estado</th>
									<th>Modificar</th>
									<th>Anular</th>
								</tr>
							</thead>
							<tbody>
								{% if boletas %}
									{% for boleta in boletas %}
										<tr>
											<td>{{boleta.boleta_numero}}</td>
											<td>{{boleta.boleta_fecha}}</td>
											<td>{{boleta.boleta_socio}}</td>
											<td>{{boleta.boleta_aporte}}</td>
											{% if boleta.boleta_estado == True %}
												<td>Agregada</td>
											{% else %}
												<td>Anulada</td>
											{% endif %}
											<td>
												<a href="{% url 'administrador:modificar_boleta' boleta.id %}" type="button" class="btn btn-primary btn-outline">Modificar</a>
											</td>
											<th><a href="{% url 'administrador:eliminar_boleta' boleta.id %}" type="button" class="btn btn-primary btn-outline">eliminar</a></th>
										</tr>
									{% endfor %}
								{% else %}
									<tr>
										<td>No hay datos</td>
										<td>-</td>
										<td>-</td>
										<td>-</td>
										<td>-</td>
										<td></td>
										<td></td>
									</tr>
								{% endif %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

<!--Load JQuery-->
<script src="{% static "mouldifi/light/js/jquery.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/bootstrap.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/metismenu/jquery.metisMenu.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/blockui-master/jquery-ui.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/blockui-master/jquery.blockUI.js" %}"></script>

<!--DataTables-->
<script src="{% static "mouldifi/light/js/plugins/datatables/jquery.dataTables.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/datatables/dataTables.bootstrap.min.js" %}></script>
<script src="{% static "mouldifi/light/js/plugins/datatables/extensions/Buttons/js/dataTables.buttons.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/datatables/jszip.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/datatables/pdfmake.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/datatables/vfs_fonts.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/datatables/extensions/Buttons/js/buttons.html5.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/datatables/extensions/Buttons/js/buttons.colVis.js" %}"></script>

<!--Float Charts-->
<script src="{% static "mouldifi/light/js/plugins/flot/jquery.flot.min.js" %}></script>
<script src="{% static "mouldifi/light/js/plugins/flot/jquery.flot.tooltip.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/flot/jquery.flot.resize.min.js" %}"></script>
<script src="{%static "mouldifi/light/js/plugins/flot/jquery.flot.selection.min.js" %}"></script>        
<script src="{% static "mouldifi/light/js/plugins/flot/jquery.flot.pie.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/flot/jquery.flot.time.min.js" %}"></script>
<script src="{% static "mouldifi/light/js/functions.js" %}"></script>
<script src="{% static "mouldifi/light/js/plugins/flot/jquery.flot.canvas.min.js" %}"></script>
<!-- DatePicker-->
<script src="{% static "mouldifi/light/js/plugins/datepicker/bootstrap-datepicker.js" %}"></script>
<script>
	$('#example').DataTable({
		language: {
	        "decimal": "",
	        "emptyTable": "No hay información",
	        "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
	        "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
	        "infoFiltered": "(Filtrado de _MAX_ total entradas)",
	        "infoPostFix": "",
	        "thousands": ",",
	        "lengthMenu": "Mostrar _MENU_ Entradas",
	        "loadingRecords": "Cargando...",
	        "processing": "Procesando...",
	        "search": "Buscar:",
	        "zeroRecords": "Sin resultados encontrados",
	        "paginate": {
	            "first": "Primero",
	            "last": "Ultimo",
	            "next": "Siguiente",
	            "previous": "Anterior"
	        }
	    }
	});
</script>